accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from accounts.views import *

urlpatterns = [
	url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
	url(r'^logout/$', logout, name='logout'),
	
	url(r'^create/$', CreateUserView.as_view(), name='create'),
]

html_css/urls.py
from django.conf.urls import url
from html_css.views import HtmlCssList

urlpatterns = [
	url(r'^list/$', HtmlCssList.as_view(), name='list'),
]

mytemplate/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    # accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    
    # html_css
    url(r'^html_css/', include('html_css.urls', namespace='html_css')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
	""" セクション """
	SECTION_CHOICES = (
		(1, 'フロントセクション'),
		(2, 'バックエンドセクション'),
		(3, '総務・経理セクション'),
		(4, 'なし'),
	)

	""" 役職 """
	position_CHOICES = (
		(1, '担当'),
		(2, '常務取締役'),
		(3, '取締役 統括'),
		(4, 'アドバイザー'),
		(5, 'セクションディレクター'),
		(6, 'エキスパート'),
	)

	section = models.IntegerField(verbose_name='セクション', choices=SECTION_CHOICES, default=1, blank=True)
	position = models.IntegerField(verbose_name='役職', choices=position_CHOICES, default=1, blank=True)

CustomUser._meta.get_field('first_name').null = False
CustomUser._meta.get_field('first_name').blank = False
CustomUser._meta.get_field('last_name').null = False
CustomUser._meta.get_field('last_name').blank = False

html_css/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from accounts.models import CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
	class Meta:
		model = CustomUser
		fields = (
			"username", "email", "password1", "password2",
			"last_name", "first_name", "section", "position",
		)
	
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'ユーザ名'
		
		self.fields['email'].widget.attrs['class'] = 'form-control'
		self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'
		
		self.fields['last_name'].widget.attrs['class'] = 'form-control'
		self.fields['last_name'].widget.attrs['placeholder'] = '姓'
		
		self.fields['first_name'].widget.attrs['class'] = 'form-control'
		self.fields['first_name'].widget.attrs['placeholder'] = '名'
		
		self.fields['section'].widget.attrs['class'] = 'form-control'
		self.fields['section'].widget.attrs['placeholder'] = 'セクション'
		
		self.fields['position'].widget.attrs['class'] = 'form-control'
		self.fields['position'].widget.attrs['placeholder'] = '役職'
		
		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'
		
		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'

accounts/views.py
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from accounts.forms import *


class CreateUserView(generic.CreateView):

    template_name = 'accounts/create.html'
    form_class = RegisterForm
    success_url = reverse_lazy('accounts:login')

cmn/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView

decorators = [login_required]


@method_decorator(decorators, name='get')
class CmnList(TemplateView):
	template_name = 'cmn/list.html'
	
	def get(self, request, *args, **kwargs):
		""""""
		user = request.user
		
		context = super(CmnList, self).get_context_data(**kwargs)
		
		return self.render_to_response(context)

html_css/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

decorators = [login_required]


@method_decorator(decorators, name='get')
class HtmlCssList(TemplateView):
	template_name = 'html_css/list.html'
	
	def get(self, request, *args, **kwargs):
		""""""
		user = request.user
		
		context = super(HtmlCssList, self).get_context_data(**kwargs)
		
		return self.render_to_response(context)

accounts/templates/accounts/create.html
{% extends "base.html" %}

{% block title %}ユーザ登録{% endblock title %}

{% block content %}
<form action="{% url 'accounts:create' %}" method="POST">
    <div class="row">
        <div class="col-sm-5 offset-sm-1">
            <div class="card">
                <div class="card-block">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.username }}
                            {{ form.username.errors }}
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.email }}
                            {{ form.email.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.password1 }}
                            {{ form.password1.errors }}
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.password2 }}
                            {{ form.password2.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.last_name }}
                            {{ form.last_name.errors }}
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.first_name }}
                            {{ form.first_name.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.section }}
                            {{ form.section.errors }}
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                            {{ form.position }}
                            {{ form.position.errors }}
                            </div>
                        </div>
                    </div>
                    {% csrf_token %}
                    <div class="btn_group">
                        <button type="submit" class="btn btn-sm btn-primary btn-outline-primary">登録</button>
                        <a href="{% url 'accounts:login' %}" class="btn btn-default btn-sm btn_back">キャンセル</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/loged_out.html
{% extends "base.html" %}

{% block title %}ログアウト{% endblock title %}

{% block content %}

    <h3 class="page-header">ログアウトしました</h3>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors  %}
    <div class="alert alert-danger" role="alert">
      <p>Your usernamne and password didn't match. Please try again.</p>
    </div>
{% endif %}

<div class="panel panel-primary" style="width: 250px;">
    <div class="panel-body">
        <form action="{% url 'accounts:login' %}" method="post" role="form">
            {% csrf_token %}
            <div class="input-group" style="margin-top: 5px">
                <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                <input id="id_username" name="username" type="text" value="" maxlength="128" placeholder="Username" aria-describedby="sizing-addon1" autofocus required/>
            </div>
            <div class="input-group" style="margin-top: 5px">
                <span class="input-group-addon"><i class="fa fa-lock fa-fw"></i></span>
                <input id="id_password" name="password" type="password" value="" maxlength="128" placeholder="Pasword" aria-describedby="sizing-addon1" required/>
            </div>

            <div style="margin-top: 5px">
                <button type="submit" class="btn btn-sm btn-primary">Login</button>
                <input name="next" type="hidden" value="{{ next }}"/>

                <a href="{% url 'accounts:create' %}" style="margin-left: 10px;">ユーザ登録はこちら</a>
            </div>
        </form>
    </div>

</div>
{% endblock %}

cmn/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>{% block title %}テンプレート{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'cmn/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'cmn/css/bootstrap-theme.min.css' %}" rel="stylesheet">
        <link href="{% static 'cmn/css/style.css' %}" rel="stylesheet">
        <script src="{% static 'cmn/js/jquery-3.2.0.min.js' %}"></script>
        <script src="{% static 'cmn/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'cmn/js/common.js' %}"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'datepicker/css/bootstrap-datepicker.min.css' %}">
        <script type="text/javascript" src="{% static 'datepicker/js/bootstrap-datepicker.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'datepicker/locales/bootstrap-datepicker.ja.min.js' %}"></script>

        <style>
            body { padding-top: 60px; }
            .navbar { min-height: 20px; }
            .navbar-brand { font-size: 16px; }
        </style>

        {% block extrahead %}{% endblock %}
    </head>

    <body>

        <div class="wrap">
            <div class="header_wrap">
                <nav class="navbar navbar-default navbar-fixed-top">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">テンプレート</a>

                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-content">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                        </div>
                        <div id="nav-content" class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                {% if not request.user.is_anonymous %}
                                <li>
                                    <a href="">ユーザ：{{ user.get_full_name|default:user.username }}</a>
                                </li>
                                <li>
                                    <a href="{% url 'accounts:logout' %}?next={{ request.path }}">Logout</a>
                                </li>
                                {% else %}
                                <li>
                                    <a href="{% url 'accounts:create' %}">ユーザ登録はこちら</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>

            <div class="content_wrap">
                <div class="container main-content">
                    {% block content %}
                        {{ content }}
                    {% endblock %}
                </div>
            </div>

            <div class="footer_wrap" style="margin-top: 30px">
                <nav class="navbar navbar-default navbar-fixed-bottom">
                    <div class="container-fluid text-center">
                        <small>Copyright (C) 2017 All Rights Reserved.</small>
                    </div>
                </nav>
            </div>

        </div>

    </body>
</html>

html_css/templates/html_css/list.html
{% extends "base.html" %}

{% block title %}テンプレート：テスト{% endblock title %}

{% block extrahead %}
<script>
    $(function() {

    });
</script>
<style>
    table {
        margin-top: 8px;
    }
    i {
        margin: 0 2px 0 2px;
    }
</style>
{% endblock %}

{% block content %}

    <div class="title">
        <h3 class="page-header">
            テスト
        </h3>
    </div>

    <div class="contents_wrap">
        <div class="section contents1">
            <ul>
                <li id="contens1_num1">111</li>
                <li id="contens1_num2">222</li>
            </ul>
            <p>コンテンツ１（pタグ）</p>
        </div>

        <div class="section contents2">
            <ul >
                <li class="warning">aaa</li>
                <li class="warning">bbb</li>
            </ul>
            <ul>
                <li>ccc</li>
                <li>ddd</li>
            </ul>
        </div>

        <div class="section contents3">
            <ul>
                <li>AAA</li>
                <li>BBB</li>
            </ul>
            <ul>
                <li>CCC</li>
                <li>DDD</li>
            </ul>
            <ul>
                <li>EEE</li>
                <li>FFF</li>
            </ul>
            <p>コンテンツ３（pタグ）</p>

            <input type="text" value="abc">
        </div>
    </div>

    <div class="row_wrap">
        <div class="section row1">
            <div class="row">
                <div class="col-md-3">3</div>
                <div class="col-md-3">6</div>
                <div class="col-md-3">9</div>
                <div class="col-md-3">12</div>
                <div class="col-md-6">6</div>
                <div class="col-md-6">12</div>
            </div>
        </div>

        <div class="section row2">
        </div>
    </div>
{% endblock content %}